# spring configuration
spring:
   application:
      name: myweb
   
   # devtools - live reload
   devtools:
      livereload:
         enabled: true
         
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
      

# server
server:
   port: 8088
    